### ISSUE TITLE
Needs a newer version of "magium/magento"

### ISSUE THREAD

**Issue by limolitz** [magium/magento1-magium-ui#22]
At the moment, "magium/magento" is required in version 0.5.22 at least. The package needs 0.7.1 at least, because it needs Magium\Util\TestCase\Configurable which was introduced in this version.

**Comment by limolitz** [comment]
No, wait. "magium/magium" is needed in version 0.7.1. Which is fine, because "magium/magento" requires it in version ~1.1. I should go home, it's too late for this.

**Comment by kschroeder** [comment]
Currently there is only a magium/magento 0.6.6.

There are several different "Magium" projects.  There is the base Magium project (magium/magium) which can be used on pretty much any website.  That library is at version 1.1.5.  Then there's the MagiumMagento project (magium/magento) which adds the Magento-specific functionality.  That library is at 0.6.6.

The class you're referring to is in the magium/magium library... except that it doesn't exist there.

**Comment by kschroeder** [comment]
:-)

Magium, itself, was originally just a Magento-based project.  Then I saw it could be used in general website testing so I split the projects apart.
